### ISSUE TITLE
Example does not demonstrate use

### ISSUE THREAD

**Issue by Adelrisk** [teobler/swr-request-generator#13]
I'd like to quote the [READEME.md](https://github.com/teobler/swr-request-generator#example)

> how to use this file can be found in `src/APP.tsx`.

The use of the library/file is non-obviously included. At least, it is not in any of the dependencies of the file:

```typescript
// https://raw.githubusercontent.com/teobler/swr-request-generator/main/example/src/App.tsx
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
```

The description implies one the following generated files is imported in the example project, but the current code does not include this.
- `example/src/request/api.ts`
- `example/src/request/client.ts`
- `example/src/request/useGetRequest.ts`
- `example/src/request/useMutationRequest.ts`

I would expect the example to demonstrate the use of the generated files.

**Comment by teobler** [comment]
You can just import them in component and call them like normal swr hook, I will update example ASAP.

**Comment by teobler** [comment]
Hi @Adelrisk updated, kindly check, `useGetRequest ` and `useMutationRequest ` are just wrapper for [swr](https://swr.vercel.app/) with [axios](https://axios-http.com/docs/intro), you can check out the docs here for more usage.
