### ISSUE TITLE
[Bug] Snake case query parameters are incorrectly camelCase'd in `use*Request()` params

### ISSUE THREAD

**Issue by NoelLH** [teobler/swr-request-generator#16]
I see a similar issue was [fixed in v1.0.0](https://github.com/teobler/swr-request-generator/releases/tag/v1.0.0) and this resolved a bug we were seeing.

However I've just stumbled on a similar one in v1.2.1 when a _query param_ is `snake_case`. This one seems to actually break the TS compilation rather than only leading to misleading interface signatures.

A snippet of input JSON which leads to the problem (inside a request's `parameters` list):

```
                    {
                        "name": "location_id",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    },
```

And here's what we get:

<img width="384" alt="Screenshot 2023-03-02 at 11 56 34" src="https://user-images.githubusercontent.com/3274454/222422122-1364f295-3a87-4a7f-92c0-c1136dae6ed1.png">

**Comment by teobler** [comment]
Thanks for report this, I think I need to further investigate this, if you can provide part of data of your json data, could be very  helpful.

**Comment by NoelLH** [comment]
@teobler I can provide a JSON response object if it helps, but I'm not sure if it will because the properties which go wrong are in the query and not the response? My description above contains the relevant JSON from the schema itself, which corresponds to parameters in the URL query. Please let me know if you need another part in particular?

**Comment by teobler** [comment]
should be ok now, you can verify it via:
- clone this repo & run `pnpm install` to install all dependencies
- put your config file in root dir(ts-codegen.config.json)
- run `pnpm start`

then files will be generated and you can have a look into it, if anything still wrong, you can reopen this or raise another issue :)

**Comment by NoelLH** [comment]
Thank you! The parameters seem to be fixed now.

The output I get has some issues around `SWRConfig` and `ResponseError`, but I believe this is just because my config follows the guidance for v1.2.1 and requires an update for some of the other changes made a couple of days ago.
