### ISSUE TITLE
Does this library support disabling of automatic revalidation 

### ISSUE THREAD

**Issue by Ol-Wood** [teobler/swr-request-generator#19]
If I disable the revalidateIfStale option then SWR does not seem to make the initial request and therefore no data is rendered/retrieved 

![Screenshot 2023-09-14 at 12 15 52](https://github.com/teobler/swr-request-generator/assets/98314947/ea2df91f-fe56-4144-99a4-93e446004079)

Is this a known issue? Any advice would be appreciated.

**Comment by teobler** [comment]
Hi @Ol-Wood , this lib just for generating functions to retrieve data by using SWR, the functions can receive all params which SWR can receive, I think you need might be this https://swr.vercel.app/docs/revalidation
