### ISSUE TITLE
Notify error for missing OperationId

### ISSUE THREAD

**Issue by nicol-ograve** [teobler/swr-request-generator#5]
If in the OpenApi endpoint the operationId is missing, the related hook is called with the generic name "useRequest".
So, if multiple endpoints don't have an operationId, the result is corrupted because is trying to export multiple functions with the same name.
An error indicating the problem would be useful to understand what underlying problem is causing the error

**Comment by teobler** [comment]
added a log for this situation, but it seems hard to notice log message in terminal, will do some enhance related to logs, leave this issue open, will close after enhance.

**Comment by teobler** [comment]
v1.2.0 released, kindly check [changelog](https://github.com/teobler/swr-request-generator/releases/tag/v1.2.0)
